# Generated by Django 4.2.4 on 2023-09-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyTask', '0002_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
