# Generated by Django 4.2.4 on 2023-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyTask', '0003_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='otp_valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
